[tools]
# pragma: allowlist nextline secret
1password = "latest"
bat = "latest"
bazel = "latest"
bazelisk = "latest"
chezmoi = "latest"
claude = "latest"
delta = "latest"
gemini = "latest"
gemini-cli = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
jq = "latest"
kafkactl = "latest"
node = "22.22.0"
pnpm = "latest"
pre-commit = "latest"
python = "3.12"
rclone = "latest"
ripgrep = "latest"
starship = "1.24.2"

[env]
